version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.17
    volumes:
      - C:\Dockerfile\db-on-docker-ms:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tgl
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - mysql
    build:
      context: .
      target: dependencies
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env
    environment:
      - MYSQL_HOST=localhost
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  mysql_volume:
